---

- name: Execute the Ansible Openstack demo-scenario2 tasks
  hosts: localhost
  vars_files:
    - vars/install-vars.yml
  tasks:
  - name: Pause for 3 minutes before detaching from source network and attach to target network.
    pause:
      minutes: 3
    
  - name: Delete test port
    os_port:
      auth:
        auth_url: "{{ os_auth }}"
        username: "{{ cloud_admin }}"
        password: "{{ admin_password }}"
        project_name: "{{ demo_project }}"
        project_domain_name: "{{ project_domain_name }}"
        user_domain_name: "{{ user_domain_name }}"
      state: absent
      name: "{{ test_port }}"

  - name: Create the second test network
    os_network:
      auth:
         auth_url: "{{ os_auth }}"
         username: "{{ cloud_admin }}"
         password: "{{ admin_password }}"
         project_name: "{{ demo_project }}"
         project_domain_name: "{{ project_domain_name }}"
         user_domain_name: "{{ user_domain_name }}"
      state: present
      name: testnet2
      external: False
      shared: False
      wait: yes
    register: testnet_network

  - name: Create the second test subnet
    os_subnet:
      auth:
         auth_url: "{{ os_auth }}"
         username: "{{ cloud_admin }}"
         password: "{{ admin_password }}"
         project_name: "{{ demo_project }}"
         project_domain_name: "{{ project_domain_name }}"
         user_domain_name: "{{ user_domain_name }}"
      state: present
      network_name: "{{ testnet_network.id }}"
      name: testnet_sub2
      ip_version: 4
      cidr: 192.168.2.0/24
      gateway_ip: 192.168.2.1
      enable_dhcp: yes
      dns_nameservers:
        - 8.8.8.8
    register: testnet_sub

  - name: Create test port
    os_port:
      auth:
        auth_url: "{{ os_auth }}"
        username: "{{ cloud_admin }}"
        password: "{{ admin_password }}"
        project_name: "{{ demo_project }}"
        project_domain_name: "{{ project_domain_name }}"
        user_domain_name: "{{ user_domain_name }}"
      state: present
      name: "{{ test_port }}"
      network: "{{ testnet_network.id }}"
      security_groups: "{{ sec_group }}"
    register: testport_port

  - name: Get token of a project
    uri:
      url: "{{ os_auth }}/auth/tokens"
      method: POST
      body_format: json
      body: '
        { "auth": {
            "identity": {
              "methods": ["password"],
              "password": {
                "user": {
                  "domain": {
                    "id": "default"
                  },
                  "name": "{{ cloud_admin }}",
                  "password": "{{ admin_password }}"
                }
              }
            },
            "scope": {
              "project": {
                "domain": {
                  "id": "default"
                },
                "name": "{{ demo_project }}"
              }
            }
          }
        }'
      status_code: 201
      HEADER_Content-Type: "application/json"
    register: token_response

  - name: Get ID of test router
    ignore_errors: yes
    os_router:
      auth:
         auth_url: "{{ os_auth }}"
         username: "{{ cloud_admin }}"
         password: "{{ admin_password }}"
         project_name: "{{ demo_project }}"
         project_domain_name: "{{ project_domain_name }}"
         user_domain_name: "{{ user_domain_name }}"
      region_name: "{{ region_name }}"
      enable_snat: yes
      state: present
      name: testnet_router
      network: "{{ ext_net }}"
    register: testnet_router

  - name: "Set OpenStack Neutron URL"
    set_fact:
      osp_neutron_url: "{{ neutron_url }}/v2.0/routers/{{ testnet_router.id }}/add_router_interface"

  - name: Attach a subnet to a server
    uri:
      url: "{{ osp_neutron_url }}"
      method: PUT
      status_code: 200
      HEADER_X-Auth-Token: "{{ token_response.x_subject_token }}"
      body_format: json
      body: '
          {
            "subnet_id": "{{ testnet_sub.id }}"
          }
          '
  - name: Get server facts
    os_server_facts:
      auth:
        auth_url: "{{ os_auth }}"
        username: "{{ cloud_admin }}"
        password: "{{ admin_password }}"
        project_name: "{{ demo_project }}"
        project_domain_name: "{{ project_domain_name }}"
        user_domain_name: "{{ user_domain_name }}"
      server: "{{ test_server }}"

  - name: "Set OpenStack Nova URL"
    set_fact:
      osp_nova_url: "{{ nova_url }}/servers/{{ openstack_servers[0].id }}/os-interface"

  - name: Attach a port to a server
    uri:
      url: "{{ osp_nova_url }}"
      method: POST
      status_code: 200
      HEADER_X-Auth-Token: "{{ token_response.x_subject_token }}"
      body_format: json
      body: '
        { "interfaceAttachment": {
            "port_id": "{{ testport_port.id }}"
          }
      }'

  - name: Attach new floating ip to server
    os_floating_ip:
      auth:
        auth_url: "{{ os_auth }}"
        username: "{{ cloud_admin }}"
        password: "{{ admin_password }}"
        project_name: "{{ demo_project }}"
        project_domain_name: "{{ project_domain_name }}"
        user_domain_name: "{{ user_domain_name }}"
      server: "{{ test_server }}"
      network: "{{ ext_net }}"

  - name: Get server facts
    os_server_facts:
      auth:
        auth_url: "{{ os_auth }}"
        username: "{{ cloud_admin }}"
        password: "{{ admin_password }}"
        project_name: "{{ demo_project }}"
        project_domain_name: "{{ project_domain_name }}"
        user_domain_name: "{{ user_domain_name }}"
      server: "{{ test_server }}"

  - name: Show test server floating IP
    debug: 
      var: openstack_servers[0].public_v4
